name: Build A05s Camera Boost

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Android project
        run: |
          ZIP=$(find . -maxdepth 1 -name "*.zip" -print -quit)
          mkdir build-project
          unzip -q "$ZIP" -d build-project

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Install Android SDK
        run: |
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: Build APK
        run: |
          gradle -p build-project assembleDebug --stacktrace -Pkotlin.jvm.target.validation.mode=warning

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: A05s-Camera-Boost-APK
          path: build-project/app/build/outputs/apk/debug/app-debug.apk
